name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Cài đặt môi trường cần thiết
    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential dpkg

    # Chạy lệnh Makefile
    - name: Run Makefile
      run: |
        sudo make install-dependence
        sudo make pack-deb

    # Đẩy file oneshot.deb lên GitHub Releases
    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3
      with:
        name: oneshot-deb
        path: oneshot.deb
